idf_component_register(
        SRCS main.c
        app/wifi_dpp.c
        app/wifi_connect.c
        driver/lvgl_driver/lvgl_init.c
        driver/lvgl_driver/lv_port_indev.c
        driver/littlefs_init.c
        gui/custom/custom.c
        gui/carousel/lv_carousel.c
        gui/dclock/lv_dclock.c
        gui/generated/events_init.c
        gui/generated/gui_guider.c
        gui/generated/setup_scr_page_main.c
        gui/generated/setup_scr_page_setting.c
        gui/generated/widgets_init.c
        gui/generated/guider_customer_fonts/lv_customer_font_LXGWWenKaiRegular_16.c
        gui/generated/guider_fonts/lv_font_Acme_Regular_16.c
        gui/generated/guider_fonts/lv_font_Alatsi_Regular_18.c
        gui/generated/guider_fonts/lv_font_LXGWWenKaiRegular_16.c
        gui/generated/guider_fonts/lv_font_montserratMedium_12.c
        gui/generated/guider_fonts/lv_font_montserratMedium_16.c
        gui/generated/guider_fonts/lv_font_montserratMedium_18.c
        gui/generated/guider_fonts/lv_font_montserratMedium_20.c
        gui/generated/guider_fonts/lv_font_montserratMedium_25.c
        

        INCLUDE_DIRS 
        ./
        app/
        driver/
        gui/
        gui/carousel
        gui/dclock
        gui/custom
        gui/generated
        gui/generated/guider_customer_fonts
        gui/generated/guider_fonts
        gui/generated/images
)
